apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(dir: 'bin', include: ['*.jar'])
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    namespace "com.google.firebase.crashlytics.unity"
    compileSdk 36
    buildToolsVersion = "36.0.0"

    defaultConfig {
        minSdk 24
        targetSdk 36
    }

    lint {
        abortOnError false
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
}
